chore: Release 2025-05-31 03:58:24 (#908)
This PR was opened by the [Changesets
release](https://github.com/changesets/action) GitHub action. When
you're ready to do a release, you can merge this and the packages will
be published to npm automatically. If you're not ready to do a release
yet, that's fine, whenever you add more changesets to main, this PR will
be updated.


# Releases
## @lynx-js/offscreen-document@0.1.0

### Minor Changes

- remove `dumpHTMLString`
([#919](https://github.com/lynx-family/lynx-stack/pull/919))

## @lynx-js/react@0.109.1

### Patch Changes

- Support the 'main-thread' directive as an alias for 'main thread'.
([#970](https://github.com/lynx-family/lynx-stack/pull/970))

- Reduce calls to `__AddInlineStyle` by pass non-literal object directly
to `__SetInlineStyles`.
([#941](https://github.com/lynx-family/lynx-stack/pull/941))

## @lynx-js/rspeedy@0.9.8

### Patch Changes

- Fix the "SyntaxError: invalid redefinition of parameter name" error.
([#949](https://github.com/lynx-family/lynx-stack/pull/949))

    Remove the default `output.iife: false` from Rspack.

## @lynx-js/react-rsbuild-plugin@0.10.2

### Patch Changes

- Fix lazy bundle build failed on Rspeedy v0.9.8 (with `output.iife:
true`). ([#972](https://github.com/lynx-family/lynx-stack/pull/972))

- Updated dependencies
\[[`81361f3`](https://github.com/lynx-family/lynx-stack/commit/81361f3c72001ffdf07f2f9f53f8e43d2ff7c961),
[`7097f52`](https://github.com/lynx-family/lynx-stack/commit/7097f52a53460527f786e2a8f150c3a907b8e722),
[`43cd520`](https://github.com/lynx-family/lynx-stack/commit/43cd520df78c3dc77aeb347a0be8c8f3ff62cc3f)]:
    -   @lynx-js/react-webpack-plugin@0.6.15
    -   @lynx-js/react-alias-rsbuild-plugin@0.10.2
    -   @lynx-js/template-webpack-plugin@0.7.1
    -   @lynx-js/react-refresh-webpack-plugin@0.3.3
    -   @lynx-js/css-extract-webpack-plugin@0.5.4

## @lynx-js/react-alias-rsbuild-plugin@0.10.2

### Patch Changes

- Resolve runtime packages in parallel using `Promise.all`.
([#955](https://github.com/lynx-family/lynx-stack/pull/955))

## @lynx-js/web-constants@0.13.4

### Patch Changes

- feat: lynx-view supports `updateGlobalProps` method, which can be used
to update lynx.\_\_globalProps
([#918](https://github.com/lynx-family/lynx-stack/pull/918))

- feat: supports `lynx.getElementById()` && `animate()`.
([#912](https://github.com/lynx-family/lynx-stack/pull/912))

After this commit, you can use `lynx.getElementById()` to get the
element by id, and use `element.animate()` to animate the element.

-   Updated dependencies \[]:
    -   @lynx-js/web-worker-rpc@0.13.4

## @lynx-js/web-core@0.13.4

### Patch Changes

- feat: lynx-view supports `updateGlobalProps` method, which can be used
to update lynx.\_\_globalProps
([#918](https://github.com/lynx-family/lynx-stack/pull/918))

- feat: supports `lynx.getElementById()` && `animate()`.
([#912](https://github.com/lynx-family/lynx-stack/pull/912))

After this commit, you can use `lynx.getElementById()` to get the
element by id, and use `element.animate()` to animate the element.

- Updated dependencies
\[[`96d3133`](https://github.com/lynx-family/lynx-stack/commit/96d3133b149b61af01c5478f4dc7b0a071137d98),
[`75e5b2f`](https://github.com/lynx-family/lynx-stack/commit/75e5b2ff16ecf5f7072a45cd130e653dee747461),
[`569618d`](https://github.com/lynx-family/lynx-stack/commit/569618d8e2665f5c9e1672f7ee5900ec2a5179a2),
[`f9f88d6`](https://github.com/lynx-family/lynx-stack/commit/f9f88d6fb9c42d3370a6622d9d799d671ffcf1a7)]:
    -   @lynx-js/web-mainthread-apis@0.13.4
    -   @lynx-js/offscreen-document@0.1.0
    -   @lynx-js/web-worker-runtime@0.13.4
    -   @lynx-js/web-constants@0.13.4
    -   @lynx-js/web-worker-rpc@0.13.4

## @lynx-js/web-core-server@0.13.4

### Patch Changes

- feat: support to dump ssrID
([#919](https://github.com/lynx-family/lynx-stack/pull/919))

## @lynx-js/web-elements@0.7.4

### Patch Changes

- fix: x-foldview-ng `overflow-y: scroll` add !important to avoid being
covered. ([#932](https://github.com/lynx-family/lynx-stack/pull/932))

-   Updated dependencies \[]:
    -   @lynx-js/web-elements-template@0.7.4

## @lynx-js/web-mainthread-apis@0.13.4

### Patch Changes

- fix: style loss issue caused by incorrect handling of
styleInfo-imports when enableCSSSelector and enableRemoveCSSScope are
turned off. ([#931](https://github.com/lynx-family/lynx-stack/pull/931))

- Updated dependencies
\[[`569618d`](https://github.com/lynx-family/lynx-stack/commit/569618d8e2665f5c9e1672f7ee5900ec2a5179a2),
[`f9f88d6`](https://github.com/lynx-family/lynx-stack/commit/f9f88d6fb9c42d3370a6622d9d799d671ffcf1a7)]:
    -   @lynx-js/web-constants@0.13.4

## @lynx-js/web-worker-runtime@0.13.4

### Patch Changes

- feat: lynx-view supports `updateGlobalProps` method, which can be used
to update lynx.\_\_globalProps
([#918](https://github.com/lynx-family/lynx-stack/pull/918))

- feat: supports `lynx.getElementById()` && `animate()`.
([#912](https://github.com/lynx-family/lynx-stack/pull/912))

After this commit, you can use `lynx.getElementById()` to get the
element by id, and use `element.animate()` to animate the element.

- Updated dependencies
\[[`96d3133`](https://github.com/lynx-family/lynx-stack/commit/96d3133b149b61af01c5478f4dc7b0a071137d98),
[`75e5b2f`](https://github.com/lynx-family/lynx-stack/commit/75e5b2ff16ecf5f7072a45cd130e653dee747461),
[`569618d`](https://github.com/lynx-family/lynx-stack/commit/569618d8e2665f5c9e1672f7ee5900ec2a5179a2),
[`f9f88d6`](https://github.com/lynx-family/lynx-stack/commit/f9f88d6fb9c42d3370a6622d9d799d671ffcf1a7)]:
    -   @lynx-js/web-mainthread-apis@0.13.4
    -   @lynx-js/offscreen-document@0.1.0
    -   @lynx-js/web-constants@0.13.4
    -   @lynx-js/web-worker-rpc@0.13.4

## @lynx-js/react-webpack-plugin@0.6.15

### Patch Changes

- Fix lazy bundle build failed on Rspeedy v0.9.8 (with `output.iife:
true`). ([#972](https://github.com/lynx-family/lynx-stack/pull/972))

## @lynx-js/template-webpack-plugin@0.7.1

### Patch Changes

- feat: Merge the absent configurations for `.web.bundle`.
([#884](https://github.com/lynx-family/lynx-stack/pull/884))

Before this change, the configuration of pageConfig in `.web.bundle` was
`compilerOptions`. After this commit, pageConfig will be a combination
of `compilerOptions` and `sourceContent.config`.

## create-rspeedy@0.9.8



## upgrade-rspeedy@0.9.8



## @lynx-js/web-elements-template@0.7.4



## @lynx-js/web-worker-rpc@0.13.4

Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>