fix(react): TypeScript error when integrating with source (#1362)
Fix errors like:

```
error TS2339: Property 'useMainThreadRef' does not exist on type 'typeof import("/home/code/lynx-stack/packages/react/types/react", { with: { "resolution-mode": "import" } })'.
```

Or

```
Cannot write file '/home/code/lynx-stack/packages/react/runtime/lib/compat/initData.d.ts' because it would overwrite input file.
```

## Checklist

<!--- Check and mark with an "x" -->

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).
- [ ] Changeset added, and when a BREAKING CHANGE occurs, it needs to be
clearly marked (or not required).


<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->
## Summary by CodeRabbit

* **Refactor**
* Simplified internal function signatures for improved code
maintainability.
* Updated configuration settings without affecting user-facing features.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->