test(tailwind-preset): avoid building tailwindcss in test (#1125)
## Summary

<!-- Can you explain the reasoning behind implementing this change? What
problem or issue does this pull request resolve? -->

The `beforeAll` hook of
`tools/tailwind-preset/src/__tests__/config.test.ts` is failing all the
time on Windows.

I'm not sure why does setting `--hookTimeout` not working (#1113,
##1121).

```
 FAIL  
tools/tailwind-preset src/__tests__/config.test.ts > Lynx Tailwind Preset
Error: Hook timed out in 10000ms.
If this is a long-running hook, pass a timeout value as the last argument or configure it globally with "hookTimeout".
```

<!-- It would be helpful if you could provide any relevant context, such
as GitHub issues or related discussions. -->

Also, the `__tests__` and `.js.map` are excluded from
`package.json#files` to reduce package size.

## Checklist

<!--- Check and mark with an "x" -->

- [x] Tests updated (or not required).
- [ ] Documentation updated (or not required).