chore: remove pnpm plugins (#1461)
The Renovate seems to stop working after
https://github.com/lynx-family/lynx-stack/pull/1447 is merged.

```
ExecError: Command failed: install-tool pnpm 10.14.0
Interrupted by SIGTERM
    at ChildProcess.<anonymous> (/usr/local/renovate/lib/util/exec/common.ts:111:11)
    at ChildProcess.emit (node:events:530:35)
    at ChildProcess.emit (node:domain:489:12)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
```

See:
https://developer.mend.io/github/lynx-family/lynx-stack/-/job/862c55c4-90b1-4597-b714-ac28b0d97884

## Checklist

<!--- Check and mark with an "x" -->

- [ ] Tests updated (or not required).
- [ ] Documentation updated (or not required).
- [ ] Changeset added, and when a BREAKING CHANGE occurs, it needs to be
clearly marked (or not required).


<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->

## Summary by CodeRabbit

* **Chores**
* Updated workspace configuration by removing an unused dependency
entry.

<!-- end of auto-generated comment: release notes by coderabbit.ai -->