chore(deps): pin `@lynx-js/types` to v3.3.0 (#938)
## Summary

<!-- Can you explain the reasoning behind implementing this change? What
problem or issue does this pull request resolve? -->

Avoid TS error introduced in `@lynx-js/types` v3.3.1.

```
Error: src/App.tsx(41,24): error TS2322: Type 'number' is not assignable to type 'string'.
Error: Process completed with exit code 2.
```
>
https://github.com/lynx-family/lynx-stack/actions/runs/15269327250/job/42941699971?pr=899

<!-- It would be helpful if you could provide any relevant context, such
as GitHub issues or related discussions. -->

## Checklist

<!--- Check and mark with an "x" -->

- [ ] Tests updated (or **not required**).
- [ ] Documentation updated (or **not required**).