fix(react/runtime): add snapshot id when throwing `ctx not found` (#1107)
## Summary

Add snapshot id report when throwing `snapshotPatchApply failed: ctx not
found` error.

We send the error to background thread to get the type of the snapshot.

before: 
```
[main-thread.js] Error: snapshotPatchApply failed: ctx not found'
```

after:
```
Error: snapshotPatchApply failed: ctx not found, snapshot type: '__Card__:__snapshot_a94a8_test_3'
```

## Checklist

- [x] Tests updated (or not required).
- [x] Documentation updated (or not required).

---------

Co-authored-by: Qingyu Wang <40660121+colinaaa@users.noreply.github.com>